### ISSUE TITLE
Double visiion during lobby select and broken when in game?

### ISSUE THREAD

**Issue by SimpForCereal** [DaXcess/LCVR#45]
might just be an compatibility issue bc of v47

During the select screen between online and lan the vision is normal, after that I get doubled vision until I enter a game.
If I host the game myself everything is fine, but if I try to join others the screen gets zoomed in, and i cant move after
![Schermafbeelding 2024-01-09 195253](https://github.com/DaXcess/LCVR/assets/156124262/8c738dcf-252c-4344-b081-ce8701854ac6)

**Comment by bavninja** [comment]
most likely morecompany is the issue its broken currently, due to the recent updates

**Comment by DaXcess** [comment]
Try running without any mods except LCVR, and also V47/V48/V49 is not officially supported by LCVR yet.

**Comment by SimpForCereal** [comment]
> Try running without any mods except LCVR, and also V47/V48/V49 is not officially supported by LCVR yet.

It only happens with MoreCompany installed, every other mod and vanilla seems to be performing fine

**Comment by DaXcess** [comment]
MoreCompany compatibility has been fixed in the latest mod versions

**Comment by PaddseL** [comment]
I still encounter this bug with newest versions from BepInEx (5.4.2100) and MoreCompany (1.7.4) from ThunderStore and latest commit of LCVR.
